// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export { }

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BarCharts: typeof import('./src/components/charts/barCharts.vue')['default']
    Base: typeof import('./src/components/base/index.vue')['default']
    Charts: typeof import('./src/components/charts/index.vue')['default']
    Config: typeof import('./src/components/config/index.vue')['default']
    ConfigBar: typeof import('./src/components/config/configBar.vue')['default']
    DatasetCharts: typeof import('./src/components/charts/datasetCharts.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FunnelCharts: typeof import('./src/components/charts/funnelCharts.vue')['default']
    LineCharts: typeof import('./src/components/charts/lineCharts.vue')['default']
    MapCharts: typeof import('./src/components/charts/mapCharts.vue')['default']
    PieCharts: typeof import('./src/components/charts/pieCharts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SankeyCharts: typeof import('./src/components/charts/sankeyCharts.vue')['default']
    SunburstCharts: typeof import('./src/components/charts/sunburstCharts.vue')['default']
    TreeCharts: typeof import('./src/components/charts/treeCharts.vue')['default']
  }
}
